# Generated by Django 5.0.1 on 2025-02-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_otp_otp_otp_created_a97b9c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='otp_otp_created_a97b9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='otp_otp_phone_n_f26c53_idx',
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', 'otp_code'], name='otp_otp_phone_n_5575f7_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', 'created_at'], name='otp_otp_phone_n_e98b28_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['otp_code', 'created_at'], name='otp_otp_otp_cod_91d0f1_idx'),
        ),
    ]
