# Generated by Django 5.0.1 on 2025-01-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_appointment_prices', '0002_alter_instantappointmentprice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantappointmentprice',
            name='site_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('video', 'Video'), ('home', 'Home')], default='clinic', help_text='Type of site for the appointment', max_length=50),
        ),
    ]
