# Generated by Django 5.0.1 on 2025-01-16 07:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text="Doctor's diagnosis")),
                ('notes', models.TextField(blank=True, help_text='Additional notes from doctor')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescribedDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text="Dosage per intake (e.g., '500mg', '2 tablets')", max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TDS', 'Three times a day'), ('QDS', 'Four times a day'), ('PRN', 'As needed'), ('STAT', 'Immediately'), ('OTHER', 'Other (see notes)')], help_text='How often to take the medication', max_length=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration of the prescription', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=10)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('injection', 'Injection'), ('inhaler', 'Inhaler'), ('drops', 'Drops'), ('other', 'Other')], default='oral', max_length=10)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for taking this medication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='drugs.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drugs', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['drug__name'],
            },
        ),
        migrations.CreateModel(
            name='TestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_recommendations', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['urgency', 'test_name'],
            },
        ),
    ]
