# Generated by Django 5.0.1 on 2025-01-04 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_arabic', models.CharField(max_length=255, verbose_name='Arabic Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drug Category',
                'verbose_name_plural': 'Drug Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugDosageForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_arabic', models.CharField(max_length=255, verbose_name='Arabic Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drug Dosage Form',
                'verbose_name_plural': 'Drug Dosage Forms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_arabic', models.CharField(max_length=255, verbose_name='Arabic Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_arabic', models.TextField(blank=True, verbose_name='Arabic Description')),
                ('strength', models.CharField(max_length=100, verbose_name='Strength')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drugs', to='drugs.drugcategory', verbose_name='Category')),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drugs', to='drugs.drugdosageform', verbose_name='Dosage Form')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['name'],
            },
        ),
    ]
