# Generated by Django 5.0.1 on 2025-01-02 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=50)),
                ('color_class', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('description_ar', models.TextField()),
                ('total_time_call', models.IntegerField()),
                ('warning_time_call', models.IntegerField()),
                ('alert_time_call', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['-created_at'],
            },
        ),
    ]
