# Generated by Django 5.0.1 on 2025-01-02 10:30

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_arabic', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('experience', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('consultant', 'Consultant'), ('specialist', 'Specialist'), ('general', 'General Practitioner')], max_length=20)),
                ('language_in_sessions', models.CharField(choices=[('arabic', 'Arabic'), ('english', 'English'), ('both', 'Both')], max_length=10)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('profile_arabic', models.TextField()),
                ('profile_english', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('iban_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialities', models.ManyToManyField(related_name='doctors', to='specialties.specialty')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
    ]
