# Generated by Django 5.0.1 on 2025-01-21 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='additional_documents',
            field=models.FileField(blank=True, help_text='Any additional supporting documents', null=True, upload_to='doctors/additional/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_document',
            field=models.FileField(blank=True, help_text='Upload your medical license document', null=True, upload_to='doctors/licenses/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification_document',
            field=models.FileField(blank=True, help_text='Upload your qualification certificates', null=True, upload_to='doctors/qualifications/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
