# Generated by Django 5.0.1 on 2025-01-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorverification',
            name='license_document',
            field=models.FileField(null=True, upload_to='temp/license_documents/'),
        ),
        migrations.AddField(
            model_name='doctorverification',
            name='qualification_document',
            field=models.FileField(null=True, upload_to='temp/qualification_documents/'),
        ),
    ]
