# Generated by Django 5.0.1 on 2025-01-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorverification_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='terms_and_privacy_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
