# Generated by Django 5.0.1 on 2025-01-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_terms_and_privacy_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorverification',
            name='sms_code',
            field=models.CharField(max_length=40),
        ),
    ]
