# Generated by Django 5.0.1 on 2025-02-02 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_bank_name_doctor_swift_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBankDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('iban_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Bank Detail',
                'verbose_name_plural': 'Doctor Bank Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
