# Generated by Django 5.0.1 on 2025-02-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_bank_details_restructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='iban_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='swift_code',
        ),
    ]
