# Generated by Django 5.0.1 on 2025-02-02 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctorschedule_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('initial_consultation', 'Initial Consultation'), ('follow_up', 'Follow Up'), ('emergency', 'Emergency'), ('specialist', 'Specialist')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_categories', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Price Category',
                'verbose_name_plural': 'Price Categories',
                'ordering': ['type'],
                'unique_together': {('doctor', 'type')},
            },
        ),
        migrations.CreateModel(
            name='DoctorDurationPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='doctors.pricecategory')),
            ],
            options={
                'verbose_name': 'Duration Price',
                'verbose_name_plural': 'Duration Prices',
                'ordering': ['duration'],
                'unique_together': {('category', 'duration')},
            },
        ),
    ]
