# Generated by Django 5.0.1 on 2025-02-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_doctor_accept_instant_appointment_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE doctors_doctorbankdetails 
                ALTER COLUMN account_holder_name DROP NOT NULL,
                ALTER COLUMN account_number DROP NOT NULL,
                ALTER COLUMN iban_number DROP NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE doctors_doctorbankdetails 
                ALTER COLUMN account_holder_name SET NOT NULL,
                ALTER COLUMN account_number SET NOT NULL,
                ALTER COLUMN iban_number SET NOT NULL;
            """
        ),
    ]
