# Generated by Django 5.0.1 on 2025-02-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_fix_bank_details_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorverification',
            name='email_code',
        ),
        migrations.RemoveField(
            model_name='doctorverification',
            name='sms_code',
        ),
    ]
