# Generated by Django 5.0.1 on 2025-02-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_fix_verification_table'),
        ('doctors', '0019_reset_verification_table'),
    ]

    operations = [
    ]
