# Generated by Django 5.0.1 on 2025-02-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_recreate_doctor_verification'),
        ('doctors', '0021_add_email_code_field'),
    ]

    operations = [
    ]
