# Generated by Django 5.0.1 on 2025-02-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_fix_verification_id_type'),
        ('doctors', '0023_doctorverification_email_code_and_more'),
    ]

    operations = [
    ]
